services:
  - name: event_management
    type: web
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    runtime: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false # Set this manually or in Render's dashboard
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: true # Automatically sync with the linked database
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: true
      - key: DB_USERNAME
        sync: true
      - key: DB_PASSWORD
        sync: true
    healthCheckPath: /
    autoDeploy: true # Automatically deploy on Git updates
    region: oregon

databases:
  - name: event_management
    plan: free
    region: oregon
